from typing import Optional, List

from pydantic import BaseModel, Field

from open_chatcaht._constants import VECTOR_SEARCH_TOP_K, SCORE_THRESHOLD
from open_chatcaht.types.chat.chat_message import ChatMessage


class FileChatParam(BaseModel):
    """File chat class"""

    query: str = Field(..., description="User input", examples=["hello"]),
    knowledge_id: str = Field(..., description="Temporary knowledge base ID"),
    top_k: int = Field(VECTOR_SEARCH_TOP_K, description="Number of matching vectors"),
    score_threshold: float = Field(
        SCORE_THRESHOLD,
        description="Knowledge base matching relevance threshold, value range between 0-1. Smaller SCORE means higher relevance; a value of 1 effectively disables filtering. Recommended around 0.5",
        ge=0,
        le=2,
    ),
    history: List[ChatMessage] = Field(
        [],
        description="Conversation history",
        examples=[
            [
                {"role": "user", "content": "Let's play idiom chain. I'll start: a lively dragon and tiger"},
                {"role": "assistant", "content": "tiger head and tiger brain"},
            ]
        ],
    ),
    stream: bool = Field(False, description="Stream output"),
    model_name: str = Field(None, description="LLM model name."),
    temperature: float = Field(0.01, description="LLM sampling temperature", ge=0.0, le=1.0),
    max_tokens: Optional[int] = Field(
        None, description="Limit the number of tokens generated by the LLM. Default None means the model's maximum"
    ),
    prompt_name: str = Field(
        "default",
        description="Name of the prompt template to use (configured in prompt_settings.yaml)",
    ),
