from typing import Optional, List, Literal

from pydantic import BaseModel, Field

from open_chatcaht._constants import MAX_TOKENS, TEMPERATURE, SCORE_THRESHOLD, VECTOR_SEARCH_TOP_K, LLM_MODEL
from open_chatcaht.types.chat.chat_message import ChatMessage


class KbChatParam(BaseModel):
    query: str = Field(..., description="User input", examples=["hello"]),
    mode: Literal["local_kb", "temp_kb", "search_engine"] = Field("local_kb", description="Knowledge source"),
    kb_name: str = Field("",
                         description="When mode=local_kb, this is the knowledge base name; when temp_kb, the temporary knowledge base ID; when search_engine, the search engine name",
                         examples=["samples"]),
    top_k: int = Field(VECTOR_SEARCH_TOP_K, description="Number of matching vectors"),
    score_threshold: float = Field(
        SCORE_THRESHOLD,
        description="Knowledge base matching relevance threshold, value range between 0-1. Smaller SCORE means higher relevance; a value of 1 effectively disables filtering. Recommended around 0.5",
        ge=0,
        le=2,
    ),
    history: List[ChatMessage] = Field(
        [],
        description="Conversation history",
        examples=[[
            {"role": "user",
             "content": "Let's play idiom chain. I'll start: a lively dragon and tiger"},
            {"role": "assistant",
             "content": "tiger head and tiger brain"}]]
    ),
    stream: bool = Field(True, description="Stream output"),
    model: str = Field(LLM_MODEL, description="LLM model name."),
    temperature: float = Field(TEMPERATURE, description="LLM sampling temperature", ge=0.0, le=2.0),
    max_tokens: Optional[int] = Field(
        MAX_TOKENS,
        description="Limit the number of tokens generated by the LLM. Default None means the model's maximum"
    ),
    prompt_name: str = Field(
        "default",
        description="Name of the prompt template to use (configured in prompt_settings.yaml)"
    ),
    return_direct: bool = Field(False, description="Return retrieval results directly without sending to the LLM"),
