from typing import Optional

from pydantic import Field, BaseModel

from open_chatcaht._constants import VS_TYPE, EMBEDDING_MODEL


class SummaryFileToVectorStoreParam(BaseModel):
    knowledge_base_name: str = Field(..., examples=["samples"]),
    file_name: str = Field(..., examples=["test.pdf"]),
    allow_empty_kb: bool = Field(True),
    vs_type: str = Field(VS_TYPE),
    embed_model: str = Field(EMBEDDING_MODEL),
    file_description: str = Field(""),
    model_name: str = Field(None, description="LLM model name."),
    temperature: float = Field(0.01, description="LLM sampling temperature", ge=0.0, le=1.0),
    max_tokens: Optional[int] = Field(
        None, description="Limit the number of tokens generated by the LLM. Default None means the model's maximum"
    ),
